### ISSUE TITLE
Lacking installation instructions

### ISSUE THREAD

**Issue by diwash007** [Bishwas-py/deviser-club#1]
It would be better if you provide the installation instructions

**Comment by Bishwas-py** [comment]
I will soon make instructions on that. Probably with in aug 8/

**Comment by Bishwas-py** [comment]
@diwash007 what do you think `Docker` a good option or just solo installation's fine?

**Comment by diwash007** [comment]
You may write instructions for both docker and direct installation.

**Comment by Bishwas-py** [comment]
@diwash007 Added the installation process..
