### ISSUE TITLE
Gotta trim leading and trailing spaces before validating text length of quick tweet

### ISSUE THREAD

**Issue by diwash007** [Bishwas-py/deviser-club#10]
![Screenshot_2022-08-13-19-59-35-932_com android chrome](https://user-images.githubusercontent.com/39879720/184498099-fcc17b62-fe3c-41c9-b787-dbbc694916e0.jpg)

**Comment by Bishwas-py** [comment]
@diwash007 It's done. Thanks for the contribution. Check this commit
> [trim leading and trailing spaces: suggested by @diwash007](https://github.com/Bishwas-py/deviser-club/commit/687a46092740914fec00e55aa3cdcae605da39c2)

**Comment by diwash007** [comment]
> @diwash007 It's done. Thanks for the contribution. Check this commit
> 
> > [trim leading and trailing spaces: suggested by @diwash007](https://github.com/Bishwas-py/deviser-club/commit/687a46092740914fec00e55aa3cdcae605da39c2)

Great!
You can use Fixes keyword on your commit message to automatically close the related issue.
"Fixes #10" in this case.
