### ISSUE TITLE
profile route not showing one's tweets

### ISSUE THREAD

**Issue by diwash007** [Bishwas-py/deviser-club#15]
check out the differences below:
one is not able to view one's tweets in order to  make changes through the profile route

![image](https://user-images.githubusercontent.com/39879720/186403500-00a21ac1-6c76-42d0-8f29-c2bb2212a3a6.png)
![image](https://user-images.githubusercontent.com/39879720/186403520-59b15979-5864-4684-b638-676f55d1dd7f.png)

**Comment by Bishwas-py** [comment]
@diwash bro, thank you very much, it's now fixed. Also, the data render in profile get shuffled/
