### ISSUE TITLE
Loading more quick tweets crashes the app

### ISSUE THREAD

**Issue by diwash007** [Bishwas-py/deviser-club#17]
Clicking on load more button leads to:
![image](https://user-images.githubusercontent.com/39879720/186404404-e493d3b7-99b5-448a-a9fd-dfe59932b1fd.png)

**Comment by Bishwas-py** [comment]
@diwash007 thanks for letting use know, we just added the ability feature, probably that is causing the issue. lemme fix it

**Comment by Bishwas-py** [comment]
It's fixed now, 
[pagy_index allowed, thanks to](https://github.com/Bishwas-py/deviser-club/commit/552e97ec0d145e11a4b787e09920a2ffae80d49e) @diwash007
