### ISSUE TITLE
site/tweet/new is not opening on an android browser

### ISSUE THREAD

**Issue by diwash007** [Bishwas-py/deviser-club#20]
browser: Chrome
version: latest as of now
android: 11

**Comment by diwash007** [comment]
![Uploading Screenshot_2022-08-24-18-06-05-558_com.android.chrome.jpg…]()

**Comment by diwash007** [comment]
![Screenshot_2022-08-24-18-06-05-558_com android chrome](https://user-images.githubusercontent.com/39879720/186417204-27705648-6685-4ba4-9372-605dd51230ff.jpg)

**Comment by Bishwas-py** [comment]
What do you think, why is it happening?

**Comment by diwash007** [comment]
> What do you think, why is it happening?

@Bishwas-py found the issue .. the user authentication is not being handled .. if I login and go to that route .. it opens .. but without being logged in .. it throws the error

**Comment by diwash007** [comment]
not only on android ..  it is on the desktop as well
