### ISSUE TITLE
Tweet count not showing on profile

### ISSUE THREAD

**Issue by diwash007** [Bishwas-py/deviser-club#5]
![image](https://user-images.githubusercontent.com/39879720/183455811-10765b4f-fbfd-4226-bd48-103ae8258ce5.png)

**Comment by Bishwas-py** [comment]
Thanks for the suggestion, it's fixed now.


![image](https://user-images.githubusercontent.com/42182303/183470351-dc8f2a08-9f22-4cb4-85db-5de7fd57bbb4.png)
