### ISSUE TITLE
Line breaks not working

### ISSUE THREAD

**Issue by diwash007** [Bishwas-py/deviser-club#6]
or is it supposed to be like this?
![image](https://user-images.githubusercontent.com/39879720/183571147-3514fbb5-7a93-4d99-b814-be9b4a9181bb.png)

**Comment by Bishwas-py** [comment]
Nope, it's not. Please give a `line break` or `space` in front of `And`

**Comment by Bishwas-py** [comment]
Probably that's because of bolding the links also?

**Comment by diwash007** [comment]
@Bishwas-py 
![image](https://user-images.githubusercontent.com/39879720/183572526-0517e59d-c03f-4f6c-a0d3-4366af1cfe5b.png)
![image](https://user-images.githubusercontent.com/39879720/183572538-665aae15-2342-4db0-8258-bb30928b9892.png)

**Comment by Bishwas-py** [comment]
I think that's beacue of `md: markdown` reader, so double line break is required, can you check it out?

**Comment by diwash007** [comment]
Figured out ... my bad .. Shift+Enter is not adding line breaks.
