### ISSUE TITLE
Setup the testing environment

### ISSUE THREAD

**Issue by LucasCarrias** [Bishwas-py/deviser-club#8]
So far this project doesn't seem to have proper testing coverage.
In my opinion, a proper testing environment can improve the health and consistency of this current project.

With that said I suggest these improvements:

- [ ] Replace Minitest by [RSpec](https://github.com/rspec/rspec-rails)
- [ ] Add [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers)
- [ ] Add [simplecov](https://github.com/simplecov-ruby/simplecov)
- [ ] Add [FactoryBot](https://github.com/thoughtbot/factory_bot_rails)
- [ ] Write specs for all use cases

All gems above are from personal preference, however, they're pretty common in many projects.

**Comment by Bishwas-py** [comment]
> [ ] Replace Minitest by [RSpec](https://github.com/rspec/rspec-rails)

Can you help us with some of these tasks?
